apiVersion: batch/v1                  
kind: Job                             
metadata:
  name: batch-job
spec:
  backoffLimit: 6
  completions: 5
  parallelism: 2
  template:
    metadata:
      labels:                         
        app: batch-job                
    spec:
      activeDeadlineSeconds: 10
      restartPolicy: OnFailure        
      containers:
      - name: main
        image: luksa/batch-job
