apiVersion: v1
kind: Pod
metadata:
  name: private-pod
spec:
  imagePullSecrets:               
  - name: mydockerhubsecret         
  containers:
  - image: eyan422/ok:v1
    name: ok
    imagePullPolicy: IfNotPresent
